---
title: "Connor Skowyra's HW 1 Dashboard"
bibliography: UMASS Data Visualization.bib
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard) # always
```

<!-- links -->
```{r}
map1link="https://github.com/dvis690-cs/hw_test/raw/main/del1Draft.rds"
viz1=url(map1link)

map2link="https://github.com/dvis690-cs/hw_test/raw/main/del2Draft.rds"
viz2=url(map2link)

map3link="https://github.com/dvis690-cs/hw_test/raw/main/del3Draft.rds"
viz3=url(map3link)

map4link="https://github.com/dvis690-cs/hw_test/raw/main/del4Draft.rds"
viz4=url(map4link)
```

## Introduction

Preparing the dashboard based on the instructions given at @magallanes_reyes_data_2022, and @aden-buie_flexdashboard_2026.

## Column {.tabset .tabset-fade}


### Bar Chart for WA Lunches

```{r}
readRDS(viz1)
```


### Histogram for WA Lunches

```{r}
readRDS(viz2)
```

### Scatterplot for WA Lunches

```{r}
readRDS(viz3)
```


### County Map for WA Lunches

```{r}
readRDS(viz4)
```



